version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      FLASK_APP: run.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - .:/app

  typecheck:
    build: .
    command: mypy app/ tests/ run.py
    working_dir: /app
    volumes:
      - .:/app

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql  

volumes:
  pgdata: